In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv("../research/sample_machine_data.csv")

In [13]:
df.head()

,machine_id,temperature,vibration,pressure,speed,torque,tool_wear,failure
0,M0001,55.50,1.69,99.79,1523.65,43.80,49.61,0
1,M0002,63.44,1.07,99.75,1500.54,35.34,14.94,0
2,M0003,65.90,1.55,102.71,1530.94,35.08,45.29,0
3,M0004,61.81,1.39,105.66,1483.66,36.21,9.84,0
4,M0005,92.07,7.32,116.76,1398.26,64.60,78.25,1

In [14]:
df.shape

(1000, 8)

In [15]:
df.columns

Index(['machine_id', 'temperature', 'vibration', 'pressure', 'speed', 'torque',
       'tool_wear', 'failure'],
      dtype='str')

In [16]:
df.isnull().sum()

machine_id     0
temperature    0
vibration      0
pressure       0
speed          0
torque         0
tool_wear      0
failure        0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   machine_id   1000 non-null   str
 1   temperature  1000 non-null   float64
 2   vibration    1000 non-null   float64
 3   pressure     1000 non-null   float64
 4   speed        1000 non-null   float64
 5   torque       1000 non-null   float64
 6   tool_wear    1000 non-null   float64
 7   failure      1000 non-null   int64
dtypes: float64(6), int64(1), str(1)
memory usage: 62.6 KB

In [19]:
df.describe()

,temperature,vibration,pressure,speed,torque,tool_wear,failure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,69.644710,3.003210,104.269040,1481.329030,44.302380,40.51735,0.188000
std,11.173987,1.692486,5.430573,49.913489,7.336042,24.43801,0.390908
min,55.020000,1.000000,98.000000,1350.260000,35.010000,5.01000,0.000000
25%,61.205000,1.827500,100.400000,1457.455000,38.650000,21.07250,0.000000
50%,67.605000,2.575000,102.835000,1490.250000,42.970000,37.12500,0.000000
75%,73.512500,3.310000,105.475000,1521.287500,46.970000,50.81000,0.000000
max,99.950000,7.990000,119.990000,1549.930000,64.930000,99.85000,1.000000

In [20]:
df["failure"].value_counts()

failure
0    812
1    188
Name: count, dtype: int64

In [21]:
df["failure"].value_counts(normalize=True) * 100

failure
0    81.2
1    18.8
Name: proportion, dtype: float64